# Call NYC OpenData API

In [2]:
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
import numpy as np
from sodapy import Socrata
import mobility_config

In [3]:
import seaborn as sns
sns.set()
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

In [4]:
client = Socrata("data.cityofnewyork.us", '7YJroGSBVCt6gzuLz6whih0yc')

# Example authenticated client (needed for non-public datasets):
client = Socrata('data.cityofnewyork.us',
                  mobility_config.app_token,
                  username=mobility_config.app_user,
                  password=mobility_config.app_pw)

# First 2000 results, returned as JSON from API / converted to Python list of
# dictionaries by sodapy.
trip_diary = client.get("kcey-vehy", limit=8000)
main_survey = client.get("jpcp-ic7c", limit=4000)
# Convert to pandas DataFrame
trip_diary_df = pd.DataFrame.from_records(trip_diary)
main_survey_df = pd.DataFrame.from_records(main_survey)

In [5]:
trip_diary_df.head()

,job,trip_id,uniqueid,qday,qday1typical,qborough_home,qsurveyzone_home,qtripdaytime,qday1tripstartcode,qday1tripstartam,qday1tripstartnoon,qday1tripstartpm,qday1trip_outsidenyc_start,qborough_start,qntacode_start,surveyzone_start,qday1tripend,qday1trip_outsidenyc_end,qborough_end,qntacode_end,surveyzone_end,qday1tripendcode,qday1triptransitto1,qday1triptransitto2,qday1triptransitto3,qday1triptransitto4,qday1triptransitto5,qday1triptransitto6,qday1triptransitto7,qday1triptransitfrom1,qday1triptransitfrom2,qday1triptransitfrom3,qday1triptransitfrom4,qday1triptransitfrom5,qday1triptransitfrom6,qday1triptransitfrom7,qday1triptravelcode01,qday1triptravelcode02,qday1triptravelcode03,qday1triptravelcode04,qday1triptravelcode05,qday1triptravelcode06,qday1triptravelcode07,qday1triptravelcode08,qday1triptravelcode09,qday1triptravelcode10,qday1triptravelcode11,qday1triptravelcode12,qday1triptravelcode13,qday1triptravelcode14,qday1triptravelcode15,qday1triptravelcode16,qday1triptravelcode17,qday1triptravelcode18,qday1triptravelcode19,qday1triptravelcode20,qday1triptravelcode21,qday1triptravelcode22,qday1triptravelcode23,qday1triptravelcode24,qday1triptravelcode25,qday1triptravelcode26,qday1triptravelcode27,qday1trippurpose,qday1triplength,qday1triplength_flt,qday1triplength_cat,qday1trippark,qday1tripparkpay,qday1tripparkpay_amount,qday1tripbikestore,number_of_trips_taken,qgender,qincome,qdisability1,qdisability2,qdisability3,qdisability4,qdisability5,qdisability6,qdisability7,qdisability8,qdisability9,qage,qagecode,qrace,qracecode,qhispanic,qeducation,qlicense,qcaraccess,qcarchange,qwelfare1,qwelfare2,qwelfare3,qwelfare4,qwelfare5,qsmartphone,qshare1,qshare2,qshare3,qshare4,qshare5,qshare6,qshare7,qshare8,qtemphigh,qtemplow,qprecipitation,qsunrise,qsunset,qcitibike,qday1triptravelcode_sp,qmodegrouping,qsustainablemode,allwt,qpurposerecode,ntacode_home
0,Online,3101674,101674,Sunday,NA,Queens,Middle Queens,NOON,Home,NA,Home,NA,NA,Queens,QN43,Outer Queens,Home,NA,Queens,QN76,Outer Queens,Home,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,No,No,No,No,No,School,11,11,11 to 15,NA,NA,NA,In your home or apartment,3 trips,Male,"$50,000 - $74,999",No,No,No,Yes,No,No,No,No,No,28,25-34,White/Caucasian,"White, Non-Hispanic","No, not of Hispanic, Latino, or Spanish origin","High school graduate or equivalent (i.e., GED)",Yes,I do not have access to a car,Reduced the number of cars it has access to,No,Yes,No,No,No,Yes,Yes,No,No,No,No,No,No,No,79,58,0,5.33,20.12,NA,Citi Bike,Bike,Yes,2.269122796,School,NaN
1,Phone,11202717,10202717,Saturday,Very typical,Queens,Middle Queens,AM,Work,Work,NA,NA,NA,Queens,NaN,NA,Home,NA,NA,NaN,NA,Home,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,No,No,No,No,No,No,Commute to/from work,27,27,26 to 30,NA,NA,NA,In your home or apartment,3 trips,Male,"$50,000 - $74,999",No,No,No,No,No,No,Yes,No,No,28,25-34,Black/ African American/ Caribbean American,"Black, Non-Hispanic","No, not of Hispanic, Latino, or Spanish origin","Bachelor's degree (i.e., BA, BS, AB)",Yes,I personally own or lease a car,The number has not changed,No,No,Yes,No,No,Yes,No,No,No,No,No,Yes,No,No,66,51,0.25,5.26,20.22,No,Personal bicycle,Bike,Yes,0.868686684,Commute to/from work,NaN
2,Phone,12202717,10202717,Saturday,Very typical,Queens,Middle Queens,NOON,Home,NA,Home,NA,NA,NA,NaN,NA,Park/Recreational area/Gym,NA,Queens,NaN,NA,Park/Recreational area/Gym,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,No,No,No,No,No,No,Social/recreation,18,18,16 to 20,NA,NA,NA,In a dedicated bike room,3 trips,Male,"$50,000 - $74,999",No,No,No,No,No,No,Yes,No,No,28,25-34,Black/ African American/ Caribbean American,"Black, Non-Hispanic","No, not of Hispanic, Latino, or Spanish origin","Bachelor's degree (i.e., BA, BS, AB)",Yes,I personally own or lease a car,The number has not changed,No,No,Yes,No,No,Yes,No,No,No,No,No,Yes,No,No,66,51,0.25,5.26,20.22,No,Personal bicycle,Bike,Yes,0.868686684,Social/recreation,NaN
3,Phone,51200330,50200330,Thursday,Very typical,Queens,Middle Queens,AM,Home,Home,NA,NA,NA,Queens,NaN,Middle Queens,Park/Recreational area/Gym,NA,Queens,NaN,Middle Queens,Park/Recreational area/Gym,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,No,No,No,No,No,No,Social/recreation,15,15,11 to 15,NA,NA,NA,In a parking garage/lot,4 trips,Male,"$50,000 - $74,999",No,No,No,No,No,No,Yes,No,No,62,55-64,White/Caucasian,"White, Non-Hispanic","No, not of Hispanic, Latino, or Spanish origin","High school graduate or equivalent (i.e., GED)",Yes,I personally own or lease a car,The number has not changed,No,No,Yes,No,No,No,No,No,No,No,No,Yes,No,No,73,57,0,5.43,20.02,No,Personal bicycle,Bike,Yes,2.43311884,Social/recreation,QN60
4,Phone,52200330,50200330,Thursday,Very typical,Queens,Middle Queens,AM,Park/Recreational area/Gym,Park/Recreational area/Gym,NA,NA,NA,Queens,NaN,Middle Queens,Home,NA,Queens,NaN,Middle Queens,Home,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,No,No,No,No,No,No,Social/recreation,15,15,11 to 15,NA,NA,NA,In a parking garage/lot,4 trips,Male,"$50,000 - $74,999",No,No,No,No,No,No,Yes,No,No,62,55-64,White/Caucasian,"White, Non-Hispanic","No, not of Hispanic, Latino, or Spanish origin","High school graduate or equivalent (i.e., GED)",Yes,I personally own or lease a car,The number has not changed,No,No,Yes,No,No,No,No,No,No,No,No,Yes,No,No,73,57,0,5.43,20.02,No,Personal bicycle,Bike,Yes,2.43311884,Social/recreation,QN60

In [11]:
main_survey_df.head()

,job,datacollection_starttime,uniqueid,qday,qntacode,qgender,qage,qagecode,qrace,qhispanic,qracecode,qeducation,qincome,qsurveyzone,qziphome,qborough,qlicense,qcaraccess,qcarmanynum,gcartype1_qcartype1_ma,gcartype1_qcartype2_ma,gcartype1_qcartype3_ma,gcartype1_qcartype4_ma,qcarhybrid1,qcarhybrid2,qcarhybrid3,qcarhybrid4,qcarhybrid5,qcarhybrid6,qcarchange,qcarreducea1,qcarreducea2,qcarreducea3,qcarreducea4,qcarreducea5,qcarreducea6,qcarreducea7,qcarreducea8,qcarreducea9,qcarincreasea1,qcarincreasea2,qcarincreasea3,qcarincreasea4,qcarincreasea5,qcarincreasea6,qcarincreasea7,qcarincreasea8,qcarincreasea9,qelectricconsider,qnoelectric1,qnoelectric2,qnoelectric3,qnoelectric4,qnoelectric5,qnoelectric6,qnoelectric7,qnoelectric8,gcarpark1_qcarpark1_ma,gcarpark1_qcarpark2_ma,gcarpark1_qcarpark3_ma,gcarpark1_qcarpark4_ma,qpaytopark,qpaytopark_amount,qshare1,qshare2,qshare3,qshare4,qshare5,qshare6,qshare7,qshare8,qsmartphone,qtripplanapp,qridehail1,qridehail2,qridehail3,qridehail4,qridehail5,qridehail6,qridehail7,qridehail8,qridehail_freq,qridehailpurpose,qbikeown,qbikemany,qbiketype1,qbiketype2,qbiketype3,qbiketype4,qbiketype5,qbikestore1,qbikestore2,qbikestore3,qbikestore4,qbikestore5,qbikestore6,qbikestore7,qbikestore8,qbikestore9,qbikeride,qbiketo,qbikedays,qbikewhy1,qbikewhy2,qbikewhy3,qbikewhy4,qbikewhy5,qbikewhy6,qbikewhy7,qbikewhy8,qbikewhynot1,qbikewhynot2,qbikewhynot3,qbikewhynot4,qbikewhynot5,qbikewhynot6,qbikewhynot7,qbikewhynot8,qbikestolen,qcitibike,qcitibikefreq,gcitibk1_qcitibikeissues1,gcitibk1_qcitibikeissues2,qnocitibike01,qnocitibike02,qnocitibike03,qnocitibike04,qnocitibike05,qnocitibike06,qnocitibike07,qnocitibike08,qnocitibike09,qnocitibike10,qnocitibike11,gfreight1b_qfreight1_ma,gfreight1b_qfreight2_ma,gfreight1b_qfreight3_ma,gfreight1b_qfreight4_ma,qpackagedeliver,qpostalstore,qsubwayservice,qsubwayimpact,qtransportnosubway01,qtransportnosubway02,qtransportnosubway03,qtransportnosubway04,qtransportnosubway05,qtransportnosubway06,qtransportnosubway07,qtransportnosubway08,qtransportnosubway09,qtransportnosubway10,qtransportnosubway11,qbusservice,qbusimpact,qtransportnobus01,qtransportnobus02,qtransportnobus03,qtransportnobus04,qtransportnobus05,qtransportnobus06,qtransportnobus07,qtransportnobus08,qtransportnobus09,qtransportnobus10,qtransportnobus11,qautovehiclefam,qautovehiclewill,qautovehiclesafe,qmarried,qwelfare1,qwelfare2,qwelfare3,qwelfare4,qwelfare5,qdisability1,qdisability2,qdisability3,qdisability4,qdisability5,qdisability6,qdisability7,qdisability8,qdisability9,qbuildingb,qrent,qchildren,gchild1_qchild1_ma,gchild1_qchild2_ma,gchild1_qchild3_ma,gchild1_qchild4_ma,qchild1schooladdr,qchild2schooladdr,qchild3schooladdr,qaccompany,qschooltravelcode01,qschooltravelcode02,qschooltravelcode03,qschooltravelcode04,qschooltravelcode05,qschooltravelcode06,qschooltravelcode07,qschooltravelcode08,qschooltravelcode09,qschooltravelcode10,qschooltravelcode11,qschooltravelcode12,qschooltravelcode13,qschooltravelcode14,qschooltravelcode15,qschooltravelcode16,qschooltravelcode17,qschooltravelcode18,qschooltravelcode19,qschooltravelcode20,qschooltravelcode21,qschooltravelcode22,qschooltravelcode23,qschooltravelcode24,qschooltravelcode25,qschooltravelcode26,qschooltravelcode27,qschooltransitto1,qschooltransitto2,qschooltransitto3,qschooltransitto4,qschooltransitto5,qschooltransitto6,qschooltransitto7,qschooltransitfrom1,qschooltransitfrom2,qschooltransitfrom3,qschooltransitfrom4,qschooltransitfrom5,qschooltransitfrom6,qschooltransitfrom7,qemployment,qemploymentcode,qindustry,gfulltime_qfulltime_ma,gfulltime_qparttime_ma,qnumberofjobs,qworklocation,qworkfh,qborough_work1,qntacode_work,qtimework,qtimehome,qborough_work2,qborough_work3,qworktravelcode01,qworktravelcode02,qworktravelcode03,qworktravelcode04,qworktravelcode05,qworktravelcode06,qworktravelcode07,qworktravelcode08,qworktravelcode09,qworktravelcode10,qworktravelcode11,qworktravelcode12,qworktravelcode13,qworktravelcode14,qworktravelcode15,qworktravelcode16,qworktravelcode17,qworktravelcode18,qworktravelcode19,qworktravelcode20,qworktravelcode21,qworktravelcode22,qworktravelcode23,qworktravelcode24,qworktravelcode25,qworktravelcode26,qworkcarpark,qworkparkpay,qworkbikepark,qschool,qlevelschool,qborough_school,qstudenttravelcode01,qstudenttravelcode02,qstudenttravelcode03,qstudenttravelcode04,qstudenttravelcode05,qstudenttravelcode06,qstudenttravelcode07,qstudenttravelcode08,qstudenttravelcode09,qstudenttravelcode10,qstudenttravelcode11,qstudenttravelcode12,qstudenttravelcode13,qstudenttravelcode14,qstudenttravelcode15,qstudenttravelcode16,qstudenttravelcode17,qstudenttravelcode18,qstudenttravelcode19,qstudenttravelcode20,qstudenttravelcode21,qstudenttravelcode22,qstudenttravelcode23,qstudenttravelcode24,qstudenttravelcode25,qstudenttravelcode26,qstudentpark,qstudentparkpay,qstudentbikepark,qlanguagepref,qlanguage2,qfreight_cmb1,qfreight_cmb2,qfreight_cmb3,qfreight_cmb4,qfreight_cmb5,qfreight_cmb6,qfreight_cmb7,qfreight_cmb8,qfreight_cmb9,allwt,qntacode_work2,qtimework2,qtimehome2,qntacode_school,qntacode_work3,qtimework3,qtimehome3,qchild4schooladdr
0,Online,13746130937,100938,Friday,QN28,Female,38,35-44,White/Caucasian,"No, not of Hispanic, Latino, or Spanish origin","White, Non-Hispanic","Graduate degree (i.e., Master's, Professional,...","$150,000-$199,999",Inner Queens,11372,Queens,Yes,"I do not personally own or lease a car, but I ...",2,Gasoline,Gasoline,NA,NA,NA,NA,NA,NA,NA,NA,The number has not changed,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,In a single family home garage or driveway,In a single family home garage or driveway,NA,NA,NA,NA,No,No,No,No,No,Yes,No,No,Yes,Daily,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,Yes,2,Yes,No,No,No,No,No,Yes,Yes,No,No,No,No,No,No,A few times a year,No,NA,NA,NA,NA,NA,NA,NA,NA,NA,No,No,No,No,No,Yes,No,No,No,No,NA,NA,NA,No,Yes,No,No,No,No,No,No,No,No,No,Less than a few times a year,Once a month,Less than a few times a year,Once a month,My lobby,NA,Getting worse,I use the subway the same amount,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,Getting better,I take the bus the same amount,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,Somewhat familiar,Not very willing,Neither more nor less safe than standard vehicles,Single,No,No,Yes,No,No,No,No,No,No,No,No,Yes,No,No,A building with 2 to 9 apartments,Own,None,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,Employed full time (working more than 30 hours...,Employed,Non-profit,1,0,1 job,At an office,"No, do not work from home",Manhattan,MN40,8:15 AM,7:00 PM,NA,NA,Yes,Yes,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,NA,NA,NA,"No, I do not attend school",NA,NA,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,NA,NA,NA,English,NA,No,No,No,No,Yes,No,Yes,No,No,0.28805089,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Online,13749321989,105388,Sunday,QN54,Male,55,55-64,White/Caucasian,"No, not of Hispanic, Latino, or Spanish origin","White, Non-Hispanic","Bachelor's degree (i.e., BA, BS, AB)","$100,000 - $149,999",Inner Brooklyn,11201,Brooklyn,Yes,I do not have access to a car,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,The number has not changed,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,Yes,No,No,No,No,No,No,No,Yes,Once a week,No,No,No,No,No,Yes,No,No,NA,NA,Yes,2,No,No,Yes,No,No,No,Yes,No,No,No,No,No,No,No,Never,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,No,No,No,No,No,Yes,No,No,No,No,NA,NA,NA,No,No,No,Yes,No,No,No,No,No,No,No,Less than a few times a year,Once a week,Less than a few times a year,A few times a month,My lobby,NA,Getting worse,I use the subway the same amount,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,Staying the same,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,Not very familiar,Not very willing,Somewhat less safe than standard vehicles,Married,No,No,Yes,No,No,No,No,No,No,No,No,Yes,No,No,A building with 10 to 49 apartments,Own,None,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,Unemployed,Unemployed,NA,NA,NA,NA,NA,NA,NA,NaN,NaN,NaN,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,"No, I do not attend school",NA,NA,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,NA,NA,NA,English,NA,No,No,Yes,Yes,No,No,Yes,No,No,1.223591243,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Online,13749324591,105415,Sunday,MN36,Male,65,65 or older,White/Caucasian,"No, not of Hispanic, Latino, or Spanish origin","White, Non-Hispanic","Bachelor's degree (i.e., BA, BS, AB)","$25,000 - $34,999",Northern Manhattan,10039,Manhattan,No,I do not have access to a car,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,The number has not changed,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,No,No,No,No,No,Yes,No,No,Yes,A few times a month,No,No,No,No,No,Yes,No,No,NA,NA,No,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,Never,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,No,No,No,No,No,Yes,No,No,No,No,NA,NA,NA,No,Yes,No,No,No,Yes,No,No,No,No,No,A few times a year,Less than a few times a year,Less than a few times a year,A few times a year,My doorstep,NA,Getting worse,I use the subway the same amount,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,Staying the same,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,Not very familiar,Somewhat willing,Neither more nor less safe than standard vehicles,Divorced,No,No,Yes,No,No,No,No,No,No,No,No,Yes,No,No,A building with 10 to 49 apartments,Rent,None,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,Retired,Not in Labor Force,NA,NA,NA,NA,NA,NA,NA,NaN,NaN,NaN,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,"No, I do not attend school",NA,NA,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,NA,NA,NA,English,NA,No,No,No,No,No,Yes,Yes,No,No,0.409953952,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Online,13745513760,100402,Friday,BX06,Male,68,65 or older,White/Caucasian,"No, not of Hispanic, Latino, or Spanish origin","White, Non-Hispanic",Some college but degree not received or in pro...,"$15,000 - $24,999",Inner Brooklyn,11205,Brooklyn,Yes,I do not have access to a car,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,The number has not changed,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,No,No,No,No,No,Yes,No,No,Yes,A few times a year,No,No,No,No,No,Yes,No,No,NA,NA,No,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,Never,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,No,No,No,No,No,Yes,No,No,No,No,NA,NA,NA,Yes,No,No,No,No,No,Yes,No,No,No,No,Less than a few times a year,Once a month,Less than a few times a year,Once a month,My lobby,NA,Getting worse,I use the subway the same amount,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,Getting worse,I take the bus the same amount,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,Somewhat familiar,Somewhat willing,Somewhat less safe than standard vehicles,Single,No,No,Yes,No,No,No,No,No,No,No,No,Yes,No,No,A building with 50 or more apartments,Own,None,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,Retired,Not in Labor Force,NA,NA,NA,NA,NA,NA,NA,NaN,NaN,NaN,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,"No, I do not attend school",NA,NA,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,NA,NA,NA,NA,NA,No,No,No,No,Yes,No,Yes,No,No,2.398325338,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Online,13745174106,100222,Monday,MN36,Male,50,45-54,White/Caucasian,"No, not of Hispanic, Latino, or Spanish origin","White, Non-Hispanic","Graduate degree (i.e., Master's, Professional,...","$200,000 and above",Outer Brooklyn,11235,Brooklyn,Yes,I do not have access to a car,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,The number has not changed,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,No,No,No,No,No,Yes,No,No,Yes,Several times a week,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,Yes,2,Yes,No,No,No,No,No,No,Yes,No,No,No,No,No,No,A few times a year,No,NA,NA,NA,NA,NA,NA,NA,NA,NA,No,No,No,No,No,Yes,No,No,Yes,No,NA,NA,NA,No,No,No,Yes,No,No,No,No,No,No,No,A few times a month,Once a week,A few times a year,Several times a week,My doorstep,NA,Staying the same,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,Getting worse,I take the bus less frequently,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,Somewhat familiar,Not very willing,Somewhat less safe than standard vehicles,Married,No,No,Yes,No,No,No,No,No,No,No,No,Yes,No,No,A building with 50 or more apartments,Own,None,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,Employed full time (working more than 30 hours...,Employed,Education,1,0,1 job,At a school or day care facility,"No, do not work from home",Brooklyn,BK17,6:45AM,"5""30PM",NA,NA,No,Yes,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,NA,NA,NA,"No, I do not attend school",NA,NA,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,NA,NA,NA,NA,NA,No,Yes,Yes,Yes,No,Yes,No,No,No,0.767818787,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
trip_diary_df.to_csv('trip_diary.csv')

In [21]:
main_survey_df.to_csv('main_survey.csv')

# EDA: Trips

In [19]:
trip_diary_df.shape

(7977, 118)

In [27]:
print(trip_diary_df.dtypes)

job                 object
trip_id             object
uniqueid            object
qday                object
qday1typical        object
                     ...
qmodegrouping       object
qsustainablemode    object
allwt               object
qpurposerecode      object
ntacode_home        object
Length: 118, dtype: object

In [28]:
trip_diary_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7977 entries, 0 to 7976
Columns: 118 entries, job to ntacode_home
dtypes: object(118)
memory usage: 7.2+ MB

In [43]:
trip_diary_df.isna().sum()

job                              0
trip_id                          0
uniqueid                         0
qday                             0
qday1typical                     0
qborough_home                    0
qsurveyzone_home                 0
qtripdaytime                     0
qday1tripstartcode               0
qday1tripstartam                 0
qday1tripstartnoon               0
qday1tripstartpm                 0
qday1trip_outsidenyc_start       0
qborough_start                   0
qntacode_start                5774
surveyzone_start                 0
qday1tripend                     0
qday1trip_outsidenyc_end         0
qborough_end                     0
qntacode_end                  5775
surveyzone_end                   0
qday1tripendcode                 0
qday1triptransitto1              0
qday1triptransitto2              0
qday1triptransitto3              0
qday1triptransitto4              0
qday1triptransitto5              0
qday1triptransitto6              0
qday1triptransitto7              0
qday1triptransitfrom1            0
qday1triptransitfrom2            0
qday1triptransitfrom3            0
qday1triptransitfrom4            0
qday1triptransitfrom5            0
qday1triptransitfrom6            0
qday1triptransitfrom7            0
qday1triptravelcode01            0
qday1triptravelcode02            0
qday1triptravelcode03            0
qday1triptravelcode04            0
qday1triptravelcode05            0
qday1triptravelcode06            0
qday1triptravelcode07            0
qday1triptravelcode08            0
qday1triptravelcode09            0
qday1triptravelcode10            0
qday1triptravelcode11            0
qday1triptravelcode12            0
qday1triptravelcode13            0
qday1triptravelcode14            0
qday1triptravelcode15            0
qday1triptravelcode16            0
qday1triptravelcode17            0
qday1triptravelcode18            0
qday1triptravelcode19            0
qday1triptravelcode20            0
qday1triptravelcode21            0
qday1triptravelcode22            0
qday1triptravelcode23            0
qday1triptravelcode24            0
qday1triptravelcode25            0
qday1triptravelcode26            0
qday1triptravelcode27            0
qday1trippurpose                 0
qday1triplength                  0
qday1triplength_flt              0
qday1triplength_cat              0
qday1trippark                    0
qday1tripparkpay                 0
qday1tripparkpay_amount          0
qday1tripbikestore               0
number_of_trips_taken            0
qgender                          0
qincome                          0
qdisability1                     0
qdisability2                     0
qdisability3                     0
qdisability4                     0
qdisability5                     0
qdisability6                     0
qdisability7                     0
qdisability8                     0
qdisability9                     0
qage                             0
qagecode                         0
qrace                            0
qracecode                        0
qhispanic                        0
qeducation                       0
qlicense                         0
qcaraccess                       0
qcarchange                       0
qwelfare1                        0
qwelfare2                        0
qwelfare3                        0
qwelfare4                        0
qwelfare5                        0
qsmartphone                      0
qshare1                          0
qshare2                          0
qshare3                          0
qshare4                          0
qshare5                          0
qshare6                          0
qshare7                          0
qshare8                          0
qtemphigh                        0
qtemplow                         0
qprecipitation                   0
qsunrise                         0
qsunset                          0
qcitibike                        0
qday1triptravelcode_sp           0
qmodegrouping                    0
qsustainablemode                 0
allwt                            0
qpurposerecode                   0
ntacode_home                  4945
dtype: int64

In [11]:
trip_diary_df.qday.value_counts()

Friday       1347
Saturday     1241
Wednesday    1181
Monday       1155
Thursday     1154
Sunday        969
Tuesday       930
Name: qday, dtype: int64

In [100]:
trip_diary_df.ntacode_home.value_counts()

BK88    75
MN12    67
BK37    63
MN03    58
BK82    47
MN13    46
BK91    45
QN12    43
MN36    41
BK61    41
BK33    40
QN08    40
BK31    39
BK35    37
BK60    37
BK95    36
MN35    36
MN32    36
BK75    36
BK78    34
BK50    32
BX14    31
BX52    30
MN34    29
MN33    28
MN14    28
BX34    28
BX05    27
BX33    27
BK73    27
BX46    26
BX09    26
BK58    25
BK81    25
MN22    25
SI05    25
QN15    25
MN23    25
MN04    24
BK64    24
BK96    23
QN21    23
MN40    23
MN15    22
BX41    22
BK29    22
MN01    22
BX13    21
BX37    21
MN17    21
BX03    21
QN10    21
BX36    20
QN31    19
BX62    19
QN28    19
QN19    19
BX43    19
MN11    19
BK32    19
QN17    18
BK45    18
BK25    18
BK69    18
BK42    18
BK85    18
BX44    17
MN31    17
QN29    17
QN55    17
QN34    17
MN19    17
MN09    17
BX35    17
QN72    16
SI12    16
MN20    16
QN51    16
QN54    16
QN30    16
BK40    16
BX63    16
BK46    16
MN06    16
QN53    15
SI08    15
BK44    15
BK68    15
BK17    14
BK77    14
BX26    14
QN46    14
SI07    14
BK38    14
BX08    14
MN21    14
MN28    13
QN22    13
SI14    13
SI36    13
BX17    13
QN61    13
BK76    13
SI22    13
BX75    12
QN71    12
MN24    12
BX28    12
QN06    11
BX30    11
QN38    11
BK79    11
QN20    11
BK83    11
QN35    10
QN49    10
BK34    10
BX01    10
QN70    10
QN45     9
QN33     9
QN76     9
BK27     9
BX06     8
MN25     8
BX22     8
BK72     8
QN26     7
QN66     7
N/A      7
BK63     7
QN23     7
SI01     7
BX29     7
SI54     7
BX40     7
BK28     7
QN25     7
QN05     7
BX55     6
BX31     6
SI28     6
QN57     6
QN44     6
QN43     6
BX27     6
BK41     6
BK99     6
BK90     6
BK93     6
BK26     6
SI24     6
QN63     6
QN37     6
SI32     6
BX10     6
BK30     5
BX39     5
BX07     5
SI48     5
QN48     5
QN07     4
QN99     4
SI45     4
QN50     4
SI11     4
QN56     4
QN01     4
QN60     4
MN27     3
MN50     3
QN03     3
QN41     3
SI25     3
BK21     2
BK43     2
SI35     2
BK19     2
BX49     2
QN52     2
QN02     1
Name: ntacode_home, dtype: int64

In [99]:
trip_diary_df.qday1trippurpose.value_counts()

Commute to/from work               2499
Other                              1140
Social/recreation                  1081
Shopping                           1051
Personal errands                    803
Dining                              434
School                              291
Medical visit (doctor's office)     285
Business                            270
Accompanying other traveler          71
NA                                   41
Refused                              11
Name: qday1trippurpose, dtype: int64

In [105]:
#make bar graph of day of week counts
# fig, ax = plt.subplots()

# # Plot a bar-chart of gold medals as a function of country
# ax.bar(['Males', 'Females'], [males['Height'].mean(), females['Height'].mean()], yerr= [males['Height'].std(), females['Height'].std(),])

# # Set the x-axis tick labels to the country names
# ax.set_xticklabels(['Males', 'Females'], rotation=90)

# # Set the y-axis label
# ax.set_ylabel("Height (cm)")

# ax.set_title('Comparing Height by Gender')

# plt.show()

Clean Data

In [44]:
#drop irrelevant columns
drop_cols_trip_diary_df = trip_diary_df.drop(columns=['job', 'qday1tripstartcode', 'qday1tripstartcode', 'qday1tripstartam',
                                            'qday1tripstartnoon', 'qday1tripstartpm', 'qday1trip_outsidenyc_start',
                                            'qday1trip_outsidenyc_end', 'qday1triptransitto1', 'qday1triptransitto2',
                                            'qday1triptransitto3', 'qday1triptransitto4', 'qday1triptransitto5',
                                            'qday1triptransitto6', 'qday1triptransitto7', 'qday1triptransitfrom1',
                                            'qday1triptransitfrom2', 'qday1triptransitfrom3', 'qday1triptransitfrom4',
                                            'qday1triptransitfrom5', 'qday1triptransitfrom6', 'qday1triptransitfrom7',
                                            'qday1triptravelcode01', 'qday1triptravelcode02', 'qday1triptravelcode03',
                                            'qday1triptravelcode04', 'qday1triptravelcode05', 'qday1triptravelcode06',
                                            'qday1triptravelcode07', 'qday1triptravelcode08', 'qday1triptravelcode09',
                                            'qday1triptravelcode10', 'qday1triptravelcode11', 'qday1triptravelcode12',
                                            'qday1triptravelcode13', 'qday1triptravelcode14', 'qday1triptravelcode15',
                                            'qday1triptravelcode16', 'qday1triptravelcode17', 'qday1triptravelcode18',
                                            'qday1triptravelcode19', 'qday1triptravelcode20', 'qday1triptravelcode21',
                                            'qday1triptravelcode22', 'qday1triptravelcode23', 'qday1triptravelcode24',
                                            'qday1triptravelcode25', 'qday1triptravelcode26', 'qday1triptravelcode27',
                                            'qday1trippurpose', 'qday1triplength', 'qday1triplength_flt','qday1trippark',
                                            'qday1tripparkpay_amount', 'qday1tripbikestore','qage', 'qrace', 'qhispanic',
                                            'qcarchange', 'qsunrise', 'qsunset', 'qday1tripparkpay'])

In [45]:
drop_cols_trip_diary_df.head()

,trip_id,uniqueid,qday,qday1typical,qborough_home,qsurveyzone_home,qtripdaytime,qborough_start,qntacode_start,surveyzone_start,qday1tripend,qborough_end,qntacode_end,surveyzone_end,qday1tripendcode,qday1triplength_cat,number_of_trips_taken,qgender,qincome,qdisability1,qdisability2,qdisability3,qdisability4,qdisability5,qdisability6,qdisability7,qdisability8,qdisability9,qagecode,qracecode,qeducation,qlicense,qcaraccess,qwelfare1,qwelfare2,qwelfare3,qwelfare4,qwelfare5,qsmartphone,qshare1,qshare2,qshare3,qshare4,qshare5,qshare6,qshare7,qshare8,qtemphigh,qtemplow,qprecipitation,qcitibike,qday1triptravelcode_sp,qmodegrouping,qsustainablemode,allwt,qpurposerecode,ntacode_home
0,3101674,101674,Sunday,NA,Queens,Middle Queens,NOON,Queens,QN43,Outer Queens,Home,Queens,QN76,Outer Queens,Home,11 to 15,3 trips,Male,"$50,000 - $74,999",No,No,No,Yes,No,No,No,No,No,25-34,"White, Non-Hispanic","High school graduate or equivalent (i.e., GED)",Yes,I do not have access to a car,No,Yes,No,No,No,Yes,Yes,No,No,No,No,No,No,No,79,58,0,NA,Citi Bike,Bike,Yes,2.269122796,School,NaN
1,11202717,10202717,Saturday,Very typical,Queens,Middle Queens,AM,Queens,NaN,NA,Home,NA,NaN,NA,Home,26 to 30,3 trips,Male,"$50,000 - $74,999",No,No,No,No,No,No,Yes,No,No,25-34,"Black, Non-Hispanic","Bachelor's degree (i.e., BA, BS, AB)",Yes,I personally own or lease a car,No,No,Yes,No,No,Yes,No,No,No,No,No,Yes,No,No,66,51,0.25,No,Personal bicycle,Bike,Yes,0.868686684,Commute to/from work,NaN
2,12202717,10202717,Saturday,Very typical,Queens,Middle Queens,NOON,NA,NaN,NA,Park/Recreational area/Gym,Queens,NaN,NA,Park/Recreational area/Gym,16 to 20,3 trips,Male,"$50,000 - $74,999",No,No,No,No,No,No,Yes,No,No,25-34,"Black, Non-Hispanic","Bachelor's degree (i.e., BA, BS, AB)",Yes,I personally own or lease a car,No,No,Yes,No,No,Yes,No,No,No,No,No,Yes,No,No,66,51,0.25,No,Personal bicycle,Bike,Yes,0.868686684,Social/recreation,NaN
3,51200330,50200330,Thursday,Very typical,Queens,Middle Queens,AM,Queens,NaN,Middle Queens,Park/Recreational area/Gym,Queens,NaN,Middle Queens,Park/Recreational area/Gym,11 to 15,4 trips,Male,"$50,000 - $74,999",No,No,No,No,No,No,Yes,No,No,55-64,"White, Non-Hispanic","High school graduate or equivalent (i.e., GED)",Yes,I personally own or lease a car,No,No,Yes,No,No,No,No,No,No,No,No,Yes,No,No,73,57,0,No,Personal bicycle,Bike,Yes,2.43311884,Social/recreation,QN60
4,52200330,50200330,Thursday,Very typical,Queens,Middle Queens,AM,Queens,NaN,Middle Queens,Home,Queens,NaN,Middle Queens,Home,11 to 15,4 trips,Male,"$50,000 - $74,999",No,No,No,No,No,No,Yes,No,No,55-64,"White, Non-Hispanic","High school graduate or equivalent (i.e., GED)",Yes,I personally own or lease a car,No,No,Yes,No,No,No,No,No,No,No,No,Yes,No,No,73,57,0,No,Personal bicycle,Bike,Yes,2.43311884,Social/recreation,QN60

In [36]:
drop_cols_trip_diary_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7977 entries, 0 to 7976
Data columns (total 58 columns):
trip_id                   7977 non-null object
uniqueid                  7977 non-null object
qday                      7977 non-null object
qday1typical              7977 non-null object
qborough_home             7977 non-null object
qsurveyzone_home          7977 non-null object
qtripdaytime              7977 non-null object
qborough_start            7977 non-null object
qntacode_start            2203 non-null object
surveyzone_start          7977 non-null object
qday1tripend              7977 non-null object
qborough_end              7977 non-null object
qntacode_end              2202 non-null object
surveyzone_end            7977 non-null object
qday1tripendcode          7977 non-null object
qday1triplength_cat       7977 non-null object
qday1tripparkpay          7977 non-null object
number_of_trips_taken     7977 non-null object
qgender                   7977 non-null object
qincome                   7977 non-null object
qdisability1              7977 non-null object
qdisability2              7977 non-null object
qdisability3              7977 non-null object
qdisability4              7977 non-null object
qdisability5              7977 non-null object
qdisability6              7977 non-null object
qdisability7              7977 non-null object
qdisability8              7977 non-null object
qdisability9              7977 non-null object
qagecode                  7977 non-null object
qracecode                 7977 non-null object
qeducation                7977 non-null object
qlicense                  7977 non-null object
qcaraccess                7977 non-null object
qwelfare1                 7977 non-null object
qwelfare2                 7977 non-null object
qwelfare3                 7977 non-null object
qwelfare4                 7977 non-null object
qwelfare5                 7977 non-null object
qsmartphone               7977 non-null object
qshare1                   7977 non-null object
qshare2                   7977 non-null object
qshare3                   7977 non-null object
qshare4                   7977 non-null object
qshare5                   7977 non-null object
qshare6                   7977 non-null object
qshare7                   7977 non-null object
qshare8                   7977 non-null object
qtemphigh                 7977 non-null object
qtemplow                  7977 non-null object
qprecipitation            7977 non-null object
qcitibike                 7977 non-null object
qday1triptravelcode_sp    7977 non-null object
qmodegrouping             7977 non-null object
qsustainablemode          7977 non-null object
allwt                     7977 non-null object
qpurposerecode            7977 non-null object
ntacode_home              3032 non-null object
dtypes: object(58)
memory usage: 3.5+ MB

In [48]:
drop_cols_trip_diary_df['qday1typical']= drop_cols_trip_diary_df['qday1typical'].replace('NA', 'Very Typical')
drop_cols_trip_diary_df['qday1tripend']= drop_cols_trip_diary_df['qday1tripend'].replace('NA', 'Home')
drop_cols_trip_diary_df['qday1tripendcode']= drop_cols_trip_diary_df['qday1tripendcode'].replace('NA', 'Home')
drop_cols_trip_diary_df['qincome']= drop_cols_trip_diary_df['qincome'].replace('NA', '$50,000 - $74,999')
drop_cols_trip_diary_df['qeducation']= drop_cols_trip_diary_df['qeducation'].replace('9', "Bachelor's degree (i.e., BA, BS, AB)")
drop_cols_trip_diary_df['qlicense']= drop_cols_trip_diary_df['qlicense'].replace('NA', 'Yes')
drop_cols_trip_diary_df['qcaraccess']= drop_cols_trip_diary_df['qcaraccess'].replace('NA', 'I personally own or lease a car')
drop_cols_trip_diary_df['qwelfare2']= drop_cols_trip_diary_df['qwelfare2'].replace('NA', 'Yes')
drop_cols_trip_diary_df['qsmartphone']= drop_cols_trip_diary_df['qsmartphone'].replace('NA', 'Yes')
drop_cols_trip_diary_df['qcitibike']= drop_cols_trip_diary_df['qcitibike'].replace('NA', 'No')
drop_cols_trip_diary_df['qpurposerecode']= drop_cols_trip_diary_df['qpurposerecode'].replace('NA', 'Commute to/from work')

In [51]:
drop_cols_trip_diary_df.head()

,trip_id,uniqueid,qday,qday1typical,qborough_home,qsurveyzone_home,qtripdaytime,qborough_start,qntacode_start,surveyzone_start,qday1tripend,qborough_end,qntacode_end,surveyzone_end,qday1tripendcode,qday1triplength_cat,number_of_trips_taken,qgender,qincome,qdisability1,qdisability2,qdisability3,qdisability4,qdisability5,qdisability6,qdisability7,qdisability8,qdisability9,qagecode,qracecode,qeducation,qlicense,qcaraccess,qwelfare1,qwelfare2,qwelfare3,qwelfare4,qwelfare5,qsmartphone,qshare1,qshare2,qshare3,qshare4,qshare5,qshare6,qshare7,qshare8,qtemphigh,qtemplow,qprecipitation,qcitibike,qday1triptravelcode_sp,qmodegrouping,qsustainablemode,allwt,qpurposerecode,ntacode_home
0,3101674,101674,Sunday,Very Typical,Queens,Middle Queens,NOON,Queens,QN43,Outer Queens,Home,Queens,QN76,Outer Queens,Home,11 to 15,3 trips,Male,"$50,000 - $74,999",No,No,No,Yes,No,No,No,No,No,25-34,"White, Non-Hispanic","High school graduate or equivalent (i.e., GED)",Yes,I do not have access to a car,No,Yes,No,No,No,Yes,Yes,No,No,No,No,No,No,No,79,58,0,No,Citi Bike,Bike,Yes,2.269122796,School,NaN
1,11202717,10202717,Saturday,Very typical,Queens,Middle Queens,AM,Queens,NaN,NA,Home,NA,NaN,NA,Home,26 to 30,3 trips,Male,"$50,000 - $74,999",No,No,No,No,No,No,Yes,No,No,25-34,"Black, Non-Hispanic","Bachelor's degree (i.e., BA, BS, AB)",Yes,I personally own or lease a car,No,No,Yes,No,No,Yes,No,No,No,No,No,Yes,No,No,66,51,0.25,No,Personal bicycle,Bike,Yes,0.868686684,Commute to/from work,NaN
2,12202717,10202717,Saturday,Very typical,Queens,Middle Queens,NOON,NA,NaN,NA,Park/Recreational area/Gym,Queens,NaN,NA,Park/Recreational area/Gym,16 to 20,3 trips,Male,"$50,000 - $74,999",No,No,No,No,No,No,Yes,No,No,25-34,"Black, Non-Hispanic","Bachelor's degree (i.e., BA, BS, AB)",Yes,I personally own or lease a car,No,No,Yes,No,No,Yes,No,No,No,No,No,Yes,No,No,66,51,0.25,No,Personal bicycle,Bike,Yes,0.868686684,Social/recreation,NaN
3,51200330,50200330,Thursday,Very typical,Queens,Middle Queens,AM,Queens,NaN,Middle Queens,Park/Recreational area/Gym,Queens,NaN,Middle Queens,Park/Recreational area/Gym,11 to 15,4 trips,Male,"$50,000 - $74,999",No,No,No,No,No,No,Yes,No,No,55-64,"White, Non-Hispanic","High school graduate or equivalent (i.e., GED)",Yes,I personally own or lease a car,No,No,Yes,No,No,No,No,No,No,No,No,Yes,No,No,73,57,0,No,Personal bicycle,Bike,Yes,2.43311884,Social/recreation,QN60
4,52200330,50200330,Thursday,Very typical,Queens,Middle Queens,AM,Queens,NaN,Middle Queens,Home,Queens,NaN,Middle Queens,Home,11 to 15,4 trips,Male,"$50,000 - $74,999",No,No,No,No,No,No,Yes,No,No,55-64,"White, Non-Hispanic","High school graduate or equivalent (i.e., GED)",Yes,I personally own or lease a car,No,No,Yes,No,No,No,No,No,No,No,No,Yes,No,No,73,57,0,No,Personal bicycle,Bike,Yes,2.43311884,Social/recreation,QN60

In [43]:
drop_cols_trip_diary_df.head()

,trip_id,uniqueid,qday,qday1typical,qborough_home,qsurveyzone_home,qtripdaytime,qborough_start,qntacode_start,surveyzone_start,qday1tripend,qborough_end,qntacode_end,surveyzone_end,qday1tripendcode,qday1triplength_cat,qday1tripparkpay,number_of_trips_taken,qgender,qincome,qdisability1,qdisability2,qdisability3,qdisability4,qdisability5,qdisability6,qdisability7,qdisability8,qdisability9,qagecode,qracecode,qeducation,qlicense,qcaraccess,qwelfare1,qwelfare2,qwelfare3,qwelfare4,qwelfare5,qsmartphone,qshare1,qshare2,qshare3,qshare4,qshare5,qshare6,qshare7,qshare8,qtemphigh,qtemplow,qprecipitation,qcitibike,qday1triptravelcode_sp,qmodegrouping,qsustainablemode,allwt,qpurposerecode,ntacode_home
0,3101674,101674,Sunday,Very Typical,Queens,Middle Queens,NOON,Queens,QN43,Outer Queens,Home,Queens,QN76,Outer Queens,Home,11 to 15,NA,3 trips,Male,"$50,000 - $74,999",No,No,No,Yes,No,No,No,No,No,25-34,"White, Non-Hispanic","High school graduate or equivalent (i.e., GED)",Yes,I do not have access to a car,No,Yes,No,No,No,Yes,Yes,No,No,No,No,No,No,No,79,58,0,NA,Citi Bike,Bike,Yes,2.269122796,School,NaN
1,11202717,10202717,Saturday,Very typical,Queens,Middle Queens,AM,Queens,NaN,NA,Home,NA,NaN,NA,Home,26 to 30,NA,3 trips,Male,"$50,000 - $74,999",No,No,No,No,No,No,Yes,No,No,25-34,"Black, Non-Hispanic","Bachelor's degree (i.e., BA, BS, AB)",Yes,I personally own or lease a car,No,No,Yes,No,No,Yes,No,No,No,No,No,Yes,No,No,66,51,0.25,No,Personal bicycle,Bike,Yes,0.868686684,Commute to/from work,NaN
2,12202717,10202717,Saturday,Very typical,Queens,Middle Queens,NOON,NA,NaN,NA,Park/Recreational area/Gym,Queens,NaN,NA,Park/Recreational area/Gym,16 to 20,NA,3 trips,Male,"$50,000 - $74,999",No,No,No,No,No,No,Yes,No,No,25-34,"Black, Non-Hispanic","Bachelor's degree (i.e., BA, BS, AB)",Yes,I personally own or lease a car,No,No,Yes,No,No,Yes,No,No,No,No,No,Yes,No,No,66,51,0.25,No,Personal bicycle,Bike,Yes,0.868686684,Social/recreation,NaN
3,51200330,50200330,Thursday,Very typical,Queens,Middle Queens,AM,Queens,NaN,Middle Queens,Park/Recreational area/Gym,Queens,NaN,Middle Queens,Park/Recreational area/Gym,11 to 15,NA,4 trips,Male,"$50,000 - $74,999",No,No,No,No,No,No,Yes,No,No,55-64,"White, Non-Hispanic","High school graduate or equivalent (i.e., GED)",Yes,I personally own or lease a car,No,No,Yes,No,No,No,No,No,No,No,No,Yes,No,No,73,57,0,No,Personal bicycle,Bike,Yes,2.43311884,Social/recreation,QN60
4,52200330,50200330,Thursday,Very typical,Queens,Middle Queens,AM,Queens,NaN,Middle Queens,Home,Queens,NaN,Middle Queens,Home,11 to 15,NA,4 trips,Male,"$50,000 - $74,999",No,No,No,No,No,No,Yes,No,No,55-64,"White, Non-Hispanic","High school graduate or equivalent (i.e., GED)",Yes,I personally own or lease a car,No,No,Yes,No,No,No,No,No,No,No,No,Yes,No,No,73,57,0,No,Personal bicycle,Bike,Yes,2.43311884,Social/recreation,QN60

# EDA: Main Survey

In [44]:
main_survey_df.shape

(3301, 331)

In [45]:
main_survey_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3301 entries, 0 to 3300
Columns: 331 entries, job to qchild4schooladdr
dtypes: object(331)
memory usage: 8.3+ MB

In [46]:
main_survey_df.isna().sum()

job                             0
datacollection_starttime        0
uniqueid                        0
qday                            0
qntacode                     1266
qgender                         0
qage                            0
qagecode                        0
qrace                           0
qhispanic                       0
qracecode                       0
qeducation                      0
qincome                         0
qsurveyzone                     0
qziphome                        2
qborough                        0
qlicense                        0
qcaraccess                      0
qcarmanynum                     0
gcartype1_qcartype1_ma          0
gcartype1_qcartype2_ma          0
gcartype1_qcartype3_ma          0
gcartype1_qcartype4_ma          0
qcarhybrid1                     0
qcarhybrid2                     0
qcarhybrid3                     0
qcarhybrid4                     0
qcarhybrid5                     0
qcarhybrid6                     0
qcarchange                      0
qcarreducea1                    0
qcarreducea2                    0
qcarreducea3                    0
qcarreducea4                    0
qcarreducea5                    0
qcarreducea6                    0
qcarreducea7                    0
qcarreducea8                    0
qcarreducea9                    0
qcarincreasea1                  0
qcarincreasea2                  0
qcarincreasea3                  0
qcarincreasea4                  0
qcarincreasea5                  0
qcarincreasea6                  0
qcarincreasea7                  0
qcarincreasea8                  0
qcarincreasea9                  0
qelectricconsider               0
qnoelectric1                    0
qnoelectric2                    0
qnoelectric3                    0
qnoelectric4                    0
qnoelectric5                    0
qnoelectric6                    0
qnoelectric7                    0
qnoelectric8                    0
gcarpark1_qcarpark1_ma          0
gcarpark1_qcarpark2_ma          0
gcarpark1_qcarpark3_ma          0
gcarpark1_qcarpark4_ma          0
qpaytopark                      0
qpaytopark_amount               0
qshare1                         0
qshare2                         0
qshare3                         0
qshare4                         0
qshare5                         0
qshare6                         0
qshare7                         0
qshare8                         0
qsmartphone                     0
qtripplanapp                    0
qridehail1                      0
qridehail2                      0
qridehail3                      0
qridehail4                      0
qridehail5                      0
qridehail6                      0
qridehail7                      0
qridehail8                      0
qridehail_freq                  0
qridehailpurpose                0
qbikeown                        0
qbikemany                       0
qbiketype1                      0
qbiketype2                      0
qbiketype3                      0
qbiketype4                      0
qbiketype5                      0
qbikestore1                     0
qbikestore2                     0
qbikestore3                     0
qbikestore4                     0
qbikestore5                     0
qbikestore6                     0
qbikestore7                     0
qbikestore8                     0
qbikestore9                     0
qbikeride                       0
qbiketo                         0
qbikedays                       0
qbikewhy1                       0
qbikewhy2                       0
qbikewhy3                       0
qbikewhy4                       0
qbikewhy5                       0
qbikewhy6                       0
qbikewhy7                       0
qbikewhy8                       0
qbikewhynot1                    0
qbikewhynot2                    0
qbikewhynot3                    0
qbikewhynot4                    0
qbikewhynot5                    0
qbikewhynot6                    0
qbikewhynot7                    0
qbikewhynot8                    0
qbikestolen                     0
qcitibike                       0
qcitibikefreq                   0
gcitibk1_qcitibikeissues1       0
gcitibk1_qcitibikeissues2       0
qnocitibike01                   0
qnocitibike02                   0
qnocitibike03                   0
qnocitibike04                   0
qnocitibike05                   0
qnocitibike06                   0
qnocitibike07                   0
qnocitibike08                   0
qnocitibike09                   0
qnocitibike10                   0
qnocitibike11                   0
gfreight1b_qfreight1_ma         0
gfreight1b_qfreight2_ma         0
gfreight1b_qfreight3_ma         0
gfreight1b_qfreight4_ma         0
qpackagedeliver                 0
qpostalstore                    0
qsubwayservice                  0
qsubwayimpact                   0
qtransportnosubway01            0
qtransportnosubway02            0
qtransportnosubway03            0
qtransportnosubway04            0
qtransportnosubway05            0
qtransportnosubway06            0
qtransportnosubway07            0
qtransportnosubway08            0
qtransportnosubway09            0
qtransportnosubway10            0
qtransportnosubway11            0
qbusservice                     0
qbusimpact                      0
qtransportnobus01               0
qtransportnobus02               0
qtransportnobus03               0
qtransportnobus04               0
qtransportnobus05               0
qtransportnobus06               0
qtransportnobus07               0
qtransportnobus08               0
qtransportnobus09               0
qtransportnobus10               0
qtransportnobus11               0
qautovehiclefam                 0
qautovehiclewill                0
qautovehiclesafe                0
qmarried                        0
qwelfare1                       0
qwelfare2                       0
qwelfare3                       0
qwelfare4                       0
qwelfare5                       0
qdisability1                    0
qdisability2                    0
qdisability3                    0
qdisability4                    0
qdisability5                    0
qdisability6                    0
qdisability7                    0
qdisability8                    0
qdisability9                    0
qbuildingb                      0
qrent                           0
qchildren                       0
gchild1_qchild1_ma              0
gchild1_qchild2_ma              0
gchild1_qchild3_ma              0
gchild1_qchild4_ma              0
qchild1schooladdr               0
qchild2schooladdr               0
qchild3schooladdr               0
qaccompany                      0
qschooltravelcode01             0
qschooltravelcode02             0
qschooltravelcode03             0
qschooltravelcode04             0
qschooltravelcode05             0
qschooltravelcode06             0
qschooltravelcode07             0
qschooltravelcode08             0
qschooltravelcode09             0
qschooltravelcode10             0
qschooltravelcode11             0
qschooltravelcode12             0
qschooltravelcode13             0
qschooltravelcode14             0
qschooltravelcode15             0
qschooltravelcode16             0
qschooltravelcode17             0
qschooltravelcode18             0
qschooltravelcode19             0
qschooltravelcode20             0
qschooltravelcode21             0
qschooltravelcode22             0
qschooltravelcode23             0
qschooltravelcode24             0
qschooltravelcode25             0
qschooltravelcode26             0
qschooltravelcode27             0
qschooltransitto1               0
qschooltransitto2               0
qschooltransitto3               0
qschooltransitto4               0
qschooltransitto5               0
qschooltransitto6               0
qschooltransitto7               0
qschooltransitfrom1             0
qschooltransitfrom2             0
qschooltransitfrom3             0
qschooltransitfrom4             0
qschooltransitfrom5             0
qschooltransitfrom6             0
qschooltransitfrom7             0
qemployment                     0
qemploymentcode                 0
qindustry                       0
gfulltime_qfulltime_ma          0
gfulltime_qparttime_ma          0
qnumberofjobs                   0
qworklocation                   0
qworkfh                         0
qborough_work1                  0
qntacode_work                2841
qtimework                    1402
qtimehome                    1402
qborough_work2                  0
qborough_work3                  0
qworktravelcode01               0
qworktravelcode02               0
qworktravelcode03               0
qworktravelcode04               0
qworktravelcode05               0
qworktravelcode06               0
qworktravelcode07               0
qworktravelcode08               0
qworktravelcode09               0
qworktravelcode10               0
qworktravelcode11               0
qworktravelcode12               0
qworktravelcode13               0
qworktravelcode14               0
qworktravelcode15               0
qworktravelcode16               0
qworktravelcode17               0
qworktravelcode18               0
qworktravelcode19               0
qworktravelcode20               0
qworktravelcode21               0
qworktravelcode22               0
qworktravelcode23               0
qworktravelcode24               0
qworktravelcode25               0
qworktravelcode26               0
qworkcarpark                    0
qworkparkpay                    0
qworkbikepark                   0
qschool                         0
qlevelschool                    0
qborough_school                 0
qstudenttravelcode01            0
qstudenttravelcode02            0
qstudenttravelcode03            0
qstudenttravelcode04            0
qstudenttravelcode05            0
qstudenttravelcode06            0
qstudenttravelcode07            0
qstudenttravelcode08            0
qstudenttravelcode09            0
qstudenttravelcode10            0
qstudenttravelcode11            0
qstudenttravelcode12            0
qstudenttravelcode13            0
qstudenttravelcode14            0
qstudenttravelcode15            0
qstudenttravelcode16            0
qstudenttravelcode17            0
qstudenttravelcode18            0
qstudenttravelcode19            0
qstudenttravelcode20            0
qstudenttravelcode21            0
qstudenttravelcode22            0
qstudenttravelcode23            0
qstudenttravelcode24            0
qstudenttravelcode25            0
qstudenttravelcode26            0
qstudentpark                    0
qstudentparkpay                 0
qstudentbikepark                0
qlanguagepref                   0
qlanguage2                      0
qfreight_cmb1                   0
qfreight_cmb2                   0
qfreight_cmb3                   0
qfreight_cmb4                   0
qfreight_cmb5                   0
qfreight_cmb6                   0
qfreight_cmb7                   0
qfreight_cmb8                   0
qfreight_cmb9                   0
allwt                           0
qntacode_work2               3222
qtimework2                   3043
qtimehome2                   3043
qntacode_school              3208
qntacode_work3               3278
qtimework3                   3249
qtimehome3                   3249
qchild4schooladdr            3255
dtype: int64