In [16]:
import pandas as pd

In [17]:
monster_data = pd.read_csv('2016_dem.csv')
monster_data.columns = monster_data.iloc[0]

In [18]:
monster_data = monster_data[1:]

In [19]:
monster_data

,Id,Id2,Geography,Id,Population Group,Estimate; TOTAL NUMBER OF RACES REPORTED - Total population,Margin of Error; TOTAL NUMBER OF RACES REPORTED - Total population,Estimate; TOTAL NUMBER OF RACES REPORTED - Total population - One race,Margin of Error; TOTAL NUMBER OF RACES REPORTED - Total population - One race,Estimate; TOTAL NUMBER OF RACES REPORTED - Total population - Two races,...,Estimate; GROSS RENT - Occupied units paying rent,Margin of Error; GROSS RENT - Occupied units paying rent,Estimate; GROSS RENT - Occupied units paying rent - Median gross rent (dollars),Margin of Error; GROSS RENT - Occupied units paying rent - Median gross rent (dollars),Estimate; COMPUTERS AND INTERNET USE - Total households,Margin of Error; COMPUTERS AND INTERNET USE - Total households,Estimate; COMPUTERS AND INTERNET USE - Total households - With a computer,Margin of Error; COMPUTERS AND INTERNET USE - Total households - With a computer,Estimate; COMPUTERS AND INTERNET USE - Total households - With a broadband Internet subscription,Margin of Error; COMPUTERS AND INTERNET USE - Total households - With a broadband Internet subscription
1,0400000US01,01,Alabama,001,Total population,4863300,*****,98.3,0.1,1.6,...,517823,10478,743,8,1852518,12189,83.9,0.4,74.7,0.5
2,0400000US02,02,Alaska,001,Total population,741894,*****,91.4,0.7,7.8,...,80663,3803,1208,34,248468,2841,93.9,0.7,85.7,1.1
3,0400000US04,04,Arizona,001,Total population,6931071,*****,96.4,0.2,3.2,...,878626,12987,976,7,2519052,11479,90.8,0.3,83.1,0.4
4,0400000US05,05,Arkansas,001,Total population,2988248,*****,97.4,0.2,2.4,...,366296,8448,701,9,1142718,7341,84.6,0.5,70.9,0.7
5,0400000US06,06,California,001,Total population,39250017,*****,95.2,0.1,4.4,...,5814710,23850,1375,5,12944178,15703,92.2,0.1,85.4,0.1
6,0400000US08,08,Colorado,001,Total population,5540545,*****,96.7,0.2,3.0,...,717127,10943,1171,10,2108992,7767,93.6,0.2,86.9,0.3
7,0400000US09,09,Connecticut,001,Total population,3576452,*****,96.9,0.2,2.8,...,457455,9082,1115,11,1357269,7141,89.3,0.5,84.1,0.6
8,0400000US10,10,Delaware,001,Total population,952065,*****,97.3,0.4,2.5,...,101349,4825,1048,25,351085,3936,90.7,0.7,83.3,0.9
9,0400000US11,11,District of Columbia,001,Total population,681170,*****,97.4,0.3,2.3,...,165747,4429,1376,32,281241,3152,89.9,1.1,79.8,1.3
10,0400000US12,12,Florida,001,Total population,20612439,*****,97.4,0.1,2.4,...,2594344,19409,1086,6,7573456,23478,90.1,0.2,81.2,0.2
11,0400000US13,13,Georgia,001,Total population,10310371,*****,97.5,0.1,2.3,...,1343035,16441,933,7,3686135,15528,89.5,0.2,80.7,0.4
12,0400000US15,15,Hawaii,001,Total population,1428557,*****,76.1,0.9,15.4,...,183461,4397,1483,28,455868,4824,91.1,0.7,83.2,0.8
13,0400000US16,16,Idaho,001,Total population,1683140,*****,97.5,0.2,2.4,...,178918,6143,790,17,610872,4143,89.7,0.7,79.4,0.9
14,0400000US17,17,Illinois,001,Total population,12801539,*****,97.5,0.1,2.3,...,1606712,17023,950,6,4822046,12932,89.2,0.2,82.0,0.3
15,0400000US18,18,Indiana,001,Total population,6633053,*****,97.6,0.1,2.3,...,759055,10989,768,6,2533270,10440,87.8,0.3,79.2,0.4
16,0400000US19,19,Iowa,001,Total population,3134693,*****,98.2,0.1,1.7,...,341654,6567,741,9,1247932,7106,88.1,0.4,79.6,0.5
17,0400000US20,20,Kansas,001,Total population,2907289,*****,96.4,0.2,3.3,...,360185,7382,789,10,1110407,6778,88.5,0.4,80.3,0.6
18,0400000US21,21,Kentucky,001,Total population,4436974,*****,97.9,0.2,2.0,...,518068,9043,707,8,1717706,9131,84.8,0.4,77.3,0.5
19,0400000US22,22,Louisiana,001,Total population,4681666,*****,98.0,0.2,1.8,...,554521,10794,808,10,1720801,8997,84.5,0.5,74.4,0.5
20,0400000US23,23,Maine,001,Total population,1331479,*****,98.0,0.2,1.9,...,139310,4904,797,23,531660,5774,88.8,0.6,80.7,0.8
21,0400000US24,24,Maryland,001,Total population,6016447,*****,96.7,0.2,3.1,...,722470,11662,1314,10,2194657,9484,91.8,0.3,85.8,0.4
22,0400000US25,25,Massachusetts,001,Total population,6811779,*****,96.9,0.2,2.9,...,947779,11697,1179,12,2579398,8290,90.7,0.3,85.5,0.3
23,0400000US26,26,Michigan,001,Total population,9928300,*****,96.9,0.1,2.8,...,1093611,14417,818,6,3884153,13696,88.4,0.2,80.5,0.3
24,0400000US27,27,Minnesota,001,Total population,5519952,*****,97.2,0.1,2.6,...,591005,8759,912,9,2148725,7378,90.2,0.2,83.5,0.3
25,0400000US28,28,Mississippi,001,Total population,2988726,*****,98.9,0.2,1.0,...,313437,8097,728,11,1091245,8803,82.1,0.6,70.7,0.7
26,0400000US29,29,Missouri,001,Total population,6093000,*****,97.5,0.1,2.3,...,756137,10606,771,6,2372190,10844,87.9,0.3,79.3,0.4
27,0400000US30,30,Montana,001,Total population,1042520,*****,96.9,0.3,2.9,...,120429,5252,741,17,416125,4426,87.8,0.6,78.9,1.0
28,0400000US31,31,Nebraska,001,Total population,1907116,*****,97.6,0.2,2.2,...,245609,5305,769,10,747562,4452,88.6,0.5,81.6,0.7
29,0400000US32,32,Nevada,001,Total population,2940058,*****,95.3,0.3,4.3,...,464864,8085,1003,13,1055158,6433,91.0,0.4,80.9,0.7
30,0400000US33,33,New Hampshire,001,Total population,1334795,*****,97.8,0.2,2.0,...,148665,5071,1026,23,520643,5191,92.3,0.5,86.4,0.8
31,0400000US34,34,New Jersey,001,Total population,8944469,*****,97.3,0.1,2.4,...,1135513,12839,1244,9,3194519,10274,90.7,0.3,84.2,0.3
32,0400000US35,35,New Mexico,001,Total population,2081015,*****,96.8,0.3,2.9,...,227499,6845,804,16,758364,6296,84.8,0.6,73.7,0.8
33,0400000US36,36,New York,001,Total population,19745289,*****,96.9,0.1,2.9,...,3247789,19458,1194,7,7209054,17665,88.7,0.2,81.7,0.2
34,0400000US37,37,North Carolina,001,Total population,10146788,*****,97.4,0.1,2.4,...,1297513,15499,839,5,3882423,16063,88.1,0.2,79.0,0.3
35,0400000US38,38,North Dakota,001,Total population,757953,*****,97.2,0.4,2.7,...,108527,3898,776,17,315134,3356,89.2,0.7,81.4,1.0
36,0400000US39,39,Ohio,001,Total population,11614373,*****,97.2,0.1,2.6,...,1522518,15099,759,4,4624669,14929,87.9,0.2,80.9,0.3
37,0400000US40,40,Oklahoma,001,Total population,3923561,*****,92.3,0.2,7.4,...,472637,7618,744,7,1469342,7193,87.3,0.4,77.2,0.4
38,0400000US41,41,Oregon,001,Total population,4093465,*****,94.9,0.3,4.7,...,575832,10745,1015,14,1571678,6691,91.7,0.4,84.9,0.5
39,0400000US42,42,Pennsylvania,001,Total population,12784227,*****,97.5,0.1,2.3,...,1468449,15057,881,5,4937771,13721,86.9,0.2,80.5,0.2
40,0400000US44,44,Rhode Island,001,Total population,1056426,*****,96.9,0.4,2.7,...,165853,5924,948,17,408239,4139,88.0,0.8,82.8,0.9
41,0400000US45,45,South Carolina,001,Total population,4961119,*****,97.8,0.2,2.0,...,538108,10971,841,9,1877887,10574,87.1,0.4,77.0,0.5
42,0400000US46,46,South Dakota,001,Total population,865454,*****,97.5,0.3,2.3,...,101969,3792,706,19,334003,3659,87.6,0.8,79.5,0.9
43,0400000US47,47,Tennessee,001,Total population,6651194,*****,97.9,0.1,2.0,...,822456,14791,806,8,2556332,11690,85.5,0.3,76.7,0.4
44,0400000US48,48,Texas,001,Total population,27862596,*****,97.4,0.1,2.4,...,3519323,23250,956,4,9535612,20125,90.0,0.2,80.5,0.2
45,0400000US49,49,Utah,001,Total population,3051217,*****,97.1,0.2,2.7,...,271441,7526,954,14,943147,4975,94.5,0.3,85.4,0.5
46,0400000US50,50,Vermont,001,Total population,624594,*****,98.0,0.3,1.8,...,71809,3429,925,21,254851,2815,89.3,0.7,81.1,0.9
47,0400000US51,51,Virginia,001,Total population,8411808,*****,96.3,0.2,3.3,...,1024547,12464,1159,13,3120692,13161,90.5,0.3,83.4,0.4
48,0400000US53,53,Washington,001,Total population,7288000,*****,94.3,0.2,5.1,...,999533,12907,1135,10,2768076,8506,93.0,0.2,87.4,0.3
49,0400000US54,54,West Virginia,001,Total population,1831102,*****,98.3,0.2,1.6,...,169814,5894,682,15,722125,5656,82.6,0.7,74.2,0.8
50,0400000US55,55,Wisconsin,001,Total population,5778709,*****,97.6,0.1,2.2,...,743037,10063,802,7,2326998,7745,88.4,0.3,81.3,0.3
51,0400000US56,56,Wyoming,001,Total population,585501,*****,97.4,0.4,2.4,...,64029,4135,840,32,223619,4088,90.8,0.9,83.2,1.3

In [20]:
monster_data.columns.str.startswith('Margin')
monster_data = monster_data.loc[:,~monster_data.columns.str.startswith('Margin')]

In [21]:
monster_data.drop(['Id', 'Id2', 'Id', 'Population Group'], axis=1, inplace=True)

/Users/brittanyfowle/opt/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:4102: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [22]:
monster_data = monster_data.T

In [23]:
monster_data.index

Index(['Geography',
       'Estimate; TOTAL NUMBER OF RACES REPORTED - Total population',
       'Estimate; TOTAL NUMBER OF RACES REPORTED - Total population - One race',
       'Estimate; TOTAL NUMBER OF RACES REPORTED - Total population - Two races',
       'Estimate; TOTAL NUMBER OF RACES REPORTED - Total population - Three races',
       'Estimate; TOTAL NUMBER OF RACES REPORTED - Total population - Four or more races',
       'Estimate; SEX AND AGE - Total population',
       'Estimate; SEX AND AGE - Total population - Male',
       'Estimate; SEX AND AGE - Total population - Female',
       'Estimate; SEX AND AGE - Under 5 years',
       ...
       'Estimate; OWNER CHARACTERISTICS - Owner-occupied housing units - Median selected monthly owner costs with a mortgage (dollars)',
       'Estimate; OWNER CHARACTERISTICS - Owner-occupied housing units - Median selected monthly owner costs without a mortgage (dollars)',
       'Estimate; GROSS RENT AS A PERCENTAGE OF HOUSEHOLD INCOME IN THE PAST 12 MONTHS - Occupied units paying rent (excluding units where GRAPI cannot be computed)',
       'Estimate; GROSS RENT AS A PERCENTAGE OF HOUSEHOLD INCOME IN THE PAST 12 MONTHS - Occupied units paying rent (excluding units where GRAPI cannot be computed) - Less than 30 percent',
       'Estimate; GROSS RENT AS A PERCENTAGE OF HOUSEHOLD INCOME IN THE PAST 12 MONTHS - Occupied units paying rent (excluding units where GRAPI cannot be computed) - 30 percent or more',
       'Estimate; GROSS RENT - Occupied units paying rent',
       'Estimate; GROSS RENT - Occupied units paying rent - Median gross rent (dollars)',
       'Estimate; COMPUTERS AND INTERNET USE - Total households',
       'Estimate; COMPUTERS AND INTERNET USE - Total households - With a computer',
       'Estimate; COMPUTERS AND INTERNET USE - Total households - With a broadband Internet subscription'],
      dtype='object', name=0, length=309)

In [84]:
monster_cols = [col for col in monster_data.index if 'Median family income' in col]
print(monster_cols)

['Estimate; INCOME IN THE PAST 12 MONTHS (IN 2014 INFLATION-ADJUSTED DOLLARS) - Families - Median family income (dollars)', 'Estimate; INCOME IN THE PAST 12 MONTHS (IN 2014 INFLATION-ADJUSTED DOLLARS) - Families - Median family income (dollars) - Married-couple family']

In [24]:
monster_data = monster_data.T

In [25]:
cols = ['Estimate; INCOME IN THE PAST 12 MONTHS (IN 2016 INFLATION-ADJUSTED DOLLARS) - Families - Median family income (dollars)']

In [26]:
df_2016 = monster_data[cols]

In [12]:
df_2016

0  Estimate; INCOME IN THE PAST 12 MONTHS (IN 2016 INFLATION-ADJUSTED DOLLARS) - Families - Median family income (dollars)
1                                               59764
2                                               88604
3                                               63877
4                                               55484
5                                               77359
6                                               80761
7                                               94449
8                                               74251
9                                               98498
10                                              61289
11                                              65018
12                                              86768
13                                              63182
14                                              76950
15                                              66032
16                                              72351
17                                              70792
18                                              59023
19                                              57490
20                                              68277
21                                              95336
22                                              95207
23                                              67330
24                                              83344
25                                              52672
26                                              65058
27                                              66288
28                                              73488
29                                              65384
30                                              86696
31                                              94546
32                                              56802
33                                              77379
34                                              62289
35                                              79530
36                                              66722
37                                              61633
38                                              70929
39                                              72313
40                                              77940
41                                              61535
42                                              70853
43                                              60659
44                                              67025
45                                              74181
46                                              74805
47                                              83306
48                                              81234
49                                              56703
50                                              72891
51                                              73574

In [27]:
df_2016.to_csv('df_2016.csv')